---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: AllyXland
# description will be included in the image's metadata
description: Bazzite gnome deck with SDDM switching.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-deck-gnome
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jc141/DwarFS/repo/fedora-%OS_VERSION%/jc141-DwarFS-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mochaa/swaync/repo/fedora-%OS_VERSION%/mochaa-swaync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wef/wlogout/repo/fedora-%OS_VERSION%/wef-wlogout-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-%OS_VERSION%/yalter-niri-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/medzik/vscode/repo/fedora-%OS_VERSION%/swayfx-swayfx-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - micro
      - starship
      - alsa-lib
      - alsa-plugins-pulseaudio
      - aquamarine
      - ark
      - bluez
      - breeze-gtk
      - brightnessctl
      - cliphist
      - code-oss
      - dolphin
      - dwarfs
      - fcitx5
      - fcitx5-autostart
      - fcitx5-data
      - fcitx5-devel
      - fcitx5-libs
      - fish
      - fontconfig
      - gnome-control-center
      - gnome-screenshot
      - gnome-settings-daemon
      - gnome-shell
      - gnome-software
      - gnome-system-monitor
      - gnome-terminal
      - gwenview
      - hellwal
      - hyprcursor
      - hyprdim
      - hyprgraphics
      - hypridle
      - hyprland
      - hyprland-contrib
      - hyprland-plugins
      - hyprland-qt-support
      - hyprland-qtutils
      - hyprlang
      - hyprlock
      - hyprnome
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprshot
      - hyprsysteminfo
      - hyprutils
      - kate
      - kcalc
      - kde-gtk-config
      - kde-settings
      - kde-style-breeze
      - kitty
      - konsole
      - kscreen
      - kwrite
      - libva
      - libvdpau
      - libxcb
      - lxappearance
      - matugen
      - micro
      - miracle-wm
      - mpvpaper
      - nautilus
      - niri
      - nodejs
      - nwg-bar
      - nwg-clipman
      - nwg-displays
      - nwg-dock
      - nwg-drawer
      - nwg-icon-picker
      - nwg-look
      - nwg-menu
      - nwg-panel
      - nwg-shell
      - nwg-shell-config
      - nwg-shell-wallpapers
      - ocl-icd
      - okular
      - openssh
      - openssh-server
      - plasma-breeze
      - plasma-desktop
      - plasma-nm
      - plasma-pa
      - plasma-systemsettings
      - plasma-workspace
      - pyprland
      - qt5-qtvirtualkeyboard
      - qt5-qtvirtualkeyboard-examples
      - qt6-qtdeclarative
      - qt6-qtsvg
      - ranger
      - rofi-wayland
      - satty
      - sddm
      - sddm-breeze
      - sddm-kcm
      - sddm-themes
      - starship
      - swappy
      - swaylock-effects
      - swww
      - tailscale
      - Thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-vcs-plugin
      - thunar-volman
      - tomlplusplus
      - traceroute
      - unclutter-xfixes
      - uwsm
      - waybar-git
      - waypaper
      - wayvnc
      - wl-clipboard
      - wlogout
      - xcb-util-image
      - xcb-util-keysyms
      - xcb-util-renderutil
      - xcb-util-wm
      - xcur2png
      - xdg-desktop-portal-hyprland
      - zsh
      - https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/compat-openssl11-1.1.1k-4.el9_0.x86_64.rpm
      - https://boosteroid.com/linux/installer/boosteroid-install-x64.rpm
      - https://github.com/ONLYOFFICE/DesktopEditors/releases/latest/download/onlyoffice-desktopeditors.x86_64.rpm
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.parsecgaming.parsec
        - com.google.Chrome
        - app.zen_browser.zen
        - org.vinegarhq.Sober
        - io.mrarm.mcpelauncher
        - org.prismlauncher.PrismLauncher
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: systemd
    system:
      enabled:
        - tailscaled
      disabled:
        []
    user: {}

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing

  - type: script
    scripts:
      - sddm/enable-sddm.sh
