---

name: AllyXland
description: Bazzite gnome deck with SDDM switching.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jc141/DwarFS/repo/fedora-%OS_VERSION%/jc141-DwarFS-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mochaa/swaync/repo/fedora-%OS_VERSION%/mochaa-swaync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wef/wlogout/repo/fedora-%OS_VERSION%/wef-wlogout-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-%OS_VERSION%/yalter-niri-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%OS_VERSION%/swayfx-swayfx-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - micro
      - starship
      - alsa-lib
      - alsa-plugins-pulseaudio
      - aquamarine
      - ark
      - bluez
      - breeze-gtk
      - brightnessctl
      - cliphist
      - code
      - dolphin
      - dwarfs
      - fcitx5
      - fcitx5-autostart
      - fcitx5-data
      - fcitx5-devel
      - fcitx5-libs
      - fish
      - fontconfig
      - glaze
      - gnome-control-center
      - gnome-screenshot
      - gnome-settings-daemon
      - gnome-shell
      - gnome-software
      - gnome-system-monitor
      - gnome-terminal
      - gwenview
      - hellwal
      - hyprcursor
      - hyprdim
      - hyprgraphics
      - hypridle
      - hyprland
      - hyprland-contrib
      - hyprland-plugins
      - hyprland-protocols
      - hyprland-qt-support
      - hyprland-qtutils
      - hyprland-welcome
      - hyprlang
      - hyprlock
      - hyprnome
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprshot
      - hyprsysteminfo
      - hyprutils
      - kate
      - kcalc
      - kde-gtk-config
      - kde-settings
      - kde-style-breeze
      - kitty
      - konsole
      - kscreen
      - kwrite
      - libva
      - libvdpau
      - libxcb
      - lxappearance
      - matugen
      - micro
      - miracle-wm
      - mpvpaper
      - nautilus
      - niri
      - nodejs
      - nwg-bar
      - nwg-clipman
      - nwg-displays
      - nwg-dock
      - nwg-drawer
      - nwg-icon-picker
      - nwg-look
      - nwg-menu
      - nwg-panel
      - nwg-shell
      - nwg-shell-config
      - nwg-shell-wallpapers
      - ocl-icd
      - okular
      - openssh
      - openssh-server
      - plasma-breeze
      - plasma-desktop
      - plasma-nm
      - plasma-pa
      - plasma-systemsettings
      - plasma-workspace
      - pyprland
      - qt5-qtvirtualkeyboard
      - qt5-qtvirtualkeyboard-examples
      - qt6-qtdeclarative
      - qt6-qtsvg
      - ranger
      - rofi-wayland
      - satty
      - scenefx
      - sddm
      - sddm-breeze
      - sddm-kcm
      - sddm-themes
      - simde
      - starship
      - swappy
      - swayfx
      - swaylock-effects
      - swww
      - tailscale
      - Thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-vcs-plugin
      - thunar-volman
      - tomlplusplus
      - traceroute
      - unclutter-xfixes
      - uwsm
      - waybar-git
      - waypaper
      - wayvnc
      - wl-clipboard
      - wlogout
      - xcb-util-image
      - xcb-util-keysyms
      - xcb-util-renderutil
      - xcb-util-wm
      - xcur2png
      - xdg-desktop-portal-hyprland
      - zsh
    remove:
      # - firefox

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.gnome.Loupe
        - com.vscodium.codium
        - org.onlyoffice.desktopeditors
    user:
      install: 
        - org.gnome.Loupe
        - com.vscodium.codium
        - org.onlyoffice.desktopeditors

  - type: systemd
    system:
      enabled:
        - tailscaled
      disabled:
        []
    user: {}

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing

  - type: script
    scripts:
      - sddm/enable-sddm.sh
