---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: allyxland  # Fixed: lowercase as per warning
description: Bazzite gnome deck with SDDM switching.

base-image: ghcr.io/ublue-os/bazzite-deck-gnome
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jc141/DwarFS/repo/fedora-%OS_VERSION%/jc141-DwarFS-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mochaa/swaync/repo/fedora-%OS_VERSION%/mochaa-swaync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wef/wlogout/repo/fedora-%OS_VERSION%/wef-wlogout-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-%OS_VERSION%/yalter-niri-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/medzik/vscode/repo/fedora-%OS_VERSION%/swayfx-swayfx-fedora-%OS_VERSION%.repo
      # Only add repos for packages you actually need that aren't in Bazzite
    install:
      # Only install what's NOT already in Bazzite
      - sddm
      - sddm-breeze
      - sddm-kcm
      - tailscale
      # Add others one by one after testing

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.parsecgaming.parsec
        - com.google.Chrome
        - app.zen_browser.zen
        - org.vinegarhq.Sober
        - io.mrarm.mcpelauncher
        - org.prismlauncher.PrismLauncher
      remove:
        - org.gnome.eog
    user: {}

  - type: systemd
    system:
      enabled:
        - tailscaled
    user: {}

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing

  - type: script
    scripts:
      - sddm/enable-sddm.sh
